[package]
name = "interpolatable-python"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
interpolatable = { path = "../interpolatable-lib" }
pythonize = "0.22.0"

[dependencies.pyo3]
version = "0.22.0"
features = ["extension-module", "abi3-py37"]
